#!/bin/sh -e

case "$1" in
start)
    echo "Telegue drive init"

    # starting Telegue NodeJS server
    cd /opt/teleguejs
    ./run.sh > /dev/null &

    ;;

stop)
    ;;

*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

